agent_name: dataset_agent
task:
model: 'dataset'

#docking
target: 
vina_program: 'qvina2'
temp_dir: 'tmp'
exhaustiveness: 1
num_sub_proc: 12
num_cpu_dock: 1
num_modes: 10
timeout_gen3d: 30
timeout_dock: 100

#pmo

#learning
seed: 1
device: cuda
max_oracle_calls: 500
batch_size: 100

#logging
wandb_log: False
wandb_entity: raj19
wandb_run_name: dockstring_dataset
freq_log: 100

#saving
save_snapshot: False
output_dir:

hydra:
  run:
    dir: ./local_exp/${agent_name}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False