agent_name: dataset_agent
data_file: data/dockstring-dataset.tsv
log_results: True
output_dir: 

#docking
target: 'fa7'
vina_program: 'qvina2'
temp_dir: 'tmp'
exhaustiveness: 1
num_sub_proc: 12
num_cpu_dock: 1
num_modes: 10
timeout_gen3d: 30
timeout_dock: 100

#learning
seed: 1
device: cuda
max_oracle_calls: 10000
batch_size: 64

#logging
wandb_log: False
wandb_entity: raj19
wandb_run_name: dockstring_dataset
freq_log: 100

#saving
save_snapshot: False

hydra:
  run:
    dir: ./local_exp/${agent_name}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False