defaults:
  - _self_ 
  - agent@_global_: 'ppo'

#describe the current run
run_name: ${seed}

#wandb
wandb_log: False
wandb_entity:
wandb_project_name: ${agent_family}-${id}
wandb_run_name: ${run_name}$

hydra:
  run:
    dir: ./checkpoint/${now:%Y.%m.%d}/${now:%H.%M.%S}_${run_name}
  job:
    chdir: False