agent_name: mb
model_name: char_rnn
dataset: zinc250k
rep: smiles
task: pmo
target: qed

#docking specific
vina_program: 'qvina2'
temp_dir: 'tmp'
exhaustiveness: 1
num_sub_proc: 12
num_cpu_dock: 1
num_modes: 10
timeout_gen3d: 30
timeout_dock: 100

#learning
seed: 1
device: cuda
max_oracle_calls: 25000
max_strings: 40000
warmup_strings: 1000
learning_rate: 0.0005
batch_size: 64
policy_batch_size: 64
reward_batch_size: 256
max_len: 100

#loss
clip_coef: 0.2
lp_coef: 5

#rnn model
num_layers: 3
hidden_size: 512
embedding_size: 128
saved_name: final_1.pt

#logging
wandb_log: False
wandb_entity: raj19
wandb_run_name: ${agent_name}_${seed}
train_log_interval: 4
env_log_interval: 100

#saving
save_snapshot: False
output_dir:

hydra:
  run:
    dir: ./local_exp/${agent_name}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False