agent_name: reinventog_agent
model_name: char_rnn
rep: smiles
task: pmo
target: qed

#data
data_file: dataset/filtered_smiles.txt
log_results: True
output_dir: 

#learning
seed: 1
device: cuda
oracle: zaleplon_mpo
prior_path: Prior.ckpt
max_oracle_calls: 25000
learning_rate: 0.0005
batch_size: 64
experience_replay: 24
sigma: 500
patience: 5

#model
num_layers: 3
hidden_size: 512
embedding_size: 128

#logging
wandb_log: False
wandb_entity: raj19
wandb_run_name: reinventog
freq_log: 100
train_log_interval: 10
env_log_interval: 100


#saving
save_snapshot: False

hydra:
  run:
    dir: ./local_exp/${agent_name}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${seed}
  job:
    chdir: False