#common
agent: 'ppo'
device: 'cuda'
torch_deterministic: True
seed: 1

#benchmark
benchmark: 'gym-classic-control'
id: 'CartPole-v1'
pomdp: False

#data collection
num_train_steps: 100000
num_envs: 4
num_steps: 128
num_minibatches: 4
update_epochs: 4
batch_size:
minibatch_size:

#learning
lr: 2.5e-4
anneal_lr: True
gamma: 0.99
gae: True
gae_lambda: 0.95
norm_adv: True
clip_vloss: True
clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl:

#saving
save_snapshot: False
save_snapshot_interval: 50000